### ISSUE TITLE
XgenTokenizer: missing _convert_token_to_id implementation

### ISSUE THREAD

**Issue by tmm1** [salesforce/xgen#10]
I ran into this trying to do LORA training, there is confusing behavior currently in the tokenizer:

```python
>>> from tokenization_xgen import XgenTokenizer
>>> x = XgenTokenizer()
>>> x.pad_token_id
>>> x.pad_token_id = 0
>>> x.pad_token_id
"b'!'"
>>> x.pad_token
"b'!'"
```

this fixes it:

```python
    def _convert_token_to_id(self, token):
        """Converts a token (str) in an id using the vocab."""
        for i in range(self.vocab_size):
            if str(self._convert_id_to_token(i)) == token:
                return i
        return None
```

cc https://github.com/oobabooga/text-generation-webui/pull/2922#issuecomment-1613920921

**Comment by tianxie-sf** [comment]
> I ran into this trying to do LORA training, there is confusing behavior currently in the tokenizer:
> 
> ```python
> >>> from tokenization_xgen import XgenTokenizer
> >>> x = XgenTokenizer()
> >>> x.pad_token_id
> >>> x.pad_token_id = 0
> >>> x.pad_token_id
> "b'!'"
> >>> x.pad_token
> "b'!'"
> ```
> 
> this fixes it:
> 
> ```python
>     def _convert_token_to_id(self, token):
>         """Converts a token (str) in an id using the vocab."""
>         for i in range(self.vocab_size):
>             if str(self._convert_id_to_token(i)) == token:
>                 return i
>         return None
> ```
> 
> cc [oobabooga/text-generation-webui#2922 (comment)](https://github.com/oobabooga/text-generation-webui/pull/2922#issuecomment-1613920921)

check our updates here: https://huggingface.co/Salesforce/xgen-7b-8k-base/blob/main/tokenization_xgen.py

**Comment by tmm1** [comment]
Thank you for the fix!
