### ISSUE TITLE
How was the training text was constructed?

### ISSUE THREAD

**Issue by deep-diver** [salesforce/xgen#2]
I saw below example from Hugging Face Hub, but it seems like `###` after `### Human: ...` isn't complete prompt template. I have tried `###` and `### Assistant: `, but in both cases text generation goes wrong
- I almost always see `<|endoftext|>`, and even after that text continues to be generated more and more
- Sometimes lots of chinese characters are generated even though I give instructions in English

Also, what is the stopping criteria for this model?

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("Salesforce/xgen-7b-8k-inst", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("Salesforce/xgen-7b-8k-inst", torch_dtype=torch.bfloat16)

header = (
    "A chat between a curious human and an artificial intelligence assistant. "
    "The assistant gives helpful, detailed, and polite answers to the human's questions.\n\n"
)
article = ""  # insert a document here
prompt = f"### Human: Please summarize the following article. {article}.\n###"

inputs = tokenizer(header + prompt, return_tensors="pt")
sample = model.generate(**inputs, max_length=128)
print(tokenizer.decode(sample[0]))
```

**Comment by rooa** [comment]
Updated the instruction HF Hub. Could you try the following definition for the prompt instead?

```python
prompt = f"### Human: Please summarize the following article.\n\n{article}.\n###"
```

**Comment by deep-diver** [comment]
yeah I tried that one.

**Comment by deep-diver** [comment]
@rooa 

that prompts generates correctly except it puts `<|endoftext|>` at the end.
also, it puts `Assistant: ` at the front. But if I include `Assistant: ` in the prompt, the generation behaviour goes weird

**Comment by deep-diver** [comment]
something like this

<img width="885" alt="aa" src="https://github.com/salesforce/xgen/assets/26025527/0e7eb111-c144-4a40-a839-ec6a33d081b3">

**Comment by rooa** [comment]
Thanks for providing more context. The model output should be truncated at `<|endoftext|>`. But let us look into it and get back to you.

**Comment by rooa** [comment]
1. The model generating "Assistant: " is expected, and should be stripped of as a postprocessing step.

```python
output = output.strip("Assistant:", "")
```

2. To truncate automatically by `<|endoftext|>`, please add `eos_token_id` in the generate function.

```python
sample = model.generate(**inputs, max_length=2048, do_sample=True, top_k=100, eos_token_id=50256)
```
(cc: @tianxie-sf , @bpucla )
